from src.gate_analyzer import GateAnalysisResult


def generate_pr_comment(result: GateAnalysisResult) -> str:
    impacted = []
    regressions = []

    for match in result.matches:
        impacted.extend(match.impacted_areas)
        regressions.extend(match.suggested_regression)

    impacted_unique = sorted(set(impacted))
    regressions_unique = sorted(set(regressions))

    lines = [
        f"## Quality Gate Result: {result.overall_risk_level.upper()} RISK",
        "",
        f"**Risk Score:** {result.overall_risk_score} / 15",
        "",
    ]

    if result.matches:
        lines.append("### Why this was flagged")
        lines.append("")
        for match in result.matches:
            source_tag = f" ({match.source})" if match.source != "keyword" else ""
            line = f"- **{match.name}{source_tag}**: matched `{', '.join(match.matched_keywords)}`; score {match.risk_score}/15"
            if match.reasoning:
                line += f" — {match.reasoning}"
            lines.append(line)
        lines.append("")

    lines.append("### Potentially impacted areas")
    lines.append("")
    if impacted_unique:
        for area in impacted_unique:
            lines.append(f"- {area}")
    else:
        lines.append("- No impacted areas detected by current rules.")

    lines.extend(["", "### Recommended before merge", ""])

    if regressions_unique:
        for item in regressions_unique:
            lines.append(f"- {item}")
    else:
        lines.append("- Manual QA review recommended.")

    if result.confidence:
        lines.extend([
            "",
            "### Confidence",
            "",
            f"- {result.confidence.level} ({result.confidence.score}/100)",
            f"- Human review required: {'yes' if result.confidence.review_required else 'no'}",
        ])

    lines.extend(["", "---", "_Generated by Quality Gate Agent v0.2_"])

    return "\n".join(lines)
